### ISSUE TITLE
USB Host

### ISSUE THREAD

**Issue by shufps** [jcmvbkbc/esp32-linux-build#10]
First of all, I'm super impressed how flawlessly the script works without any fixed or adjustments, just start it and at the end there is a fully running Linux :exploding_head: 

Thx a lot for providing this :raised_hands: 

What I wonder, Is there an easy way to enable USB Host on the ESP32-S?

I would like to connect a USB CDC ACM (virtual com port) USB-Device onto my ESP32-S3 board but it doesn't work out-of-the-box :thinking: 

I would be very grateful if you could point me in the right direction :hugs:

**Comment by jcmvbkbc** [comment]
> Hmm in make menuconfig, in the esp32s3_defconfig and .config there is no sign of USB ...
> Maybe it doesn't exist?

That's correct. ATM there's no kernel driver for the esp32s3 USB host controller, so no point in enabling the USB subsystem. The USB serial peripheral is not related to the USB host controller.

**Comment by jcmvbkbc** [comment]
Not sure when [this](https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-reference/peripherals/usb_host/usb_host_notes_dwc_otg.html) page was published, but it looks like we may have a linux driver for the USB controller after all. I'll try to configure it.

**Comment by jcmvbkbc** [comment]
USB host has been added to the Box3 configuration with support for HID and mass storage devices. Details: https://github.com/jcmvbkbc/linux-xtensa/commit/edfcd34a31ac068c782bb9e4774f5ad6fce31fb8, https://github.com/jcmvbkbc/linux-xtensa/commit/614dc351334dfbb987274f066dc87965d89bd51c, https://github.com/jcmvbkbc/linux-xtensa/commit/87fd6def2e1e6b6f7806a3d587fa89235924576c, https://github.com/jcmvbkbc/linux-xtensa/commit/46241bfe047cad52a9520f0196059f698e8dfb6b and https://github.com/jcmvbkbc/buildroot/commit/4e75fe642b424cb280afdf83e9d13fa0fb062185
