### ISSUE TITLE
Documentation wiki offline

### ISSUE THREAD

**Issue by a-v-s** [jcmvbkbc/esp32-linux-build#3]
In the side bar there is the url http://wiki.osll.ru/doku.php/etc:users:jcmvbkbc:linux-xtensa:esp32s3 
However, the server wiki.osll.ru appears to be offline

**Comment by Chandler-Kluser** [comment]
I have noticed that, too

It is not available anymore

**Comment by jcmvbkbc** [comment]
It's back online.
